import type { Metadata } from "next"
import { Pixelify_Sans } from "next/font/google"
import "./globals.css"

const pixel = Pixelify_Sans({
  weight: ["400", "500", "600", "700"],
  style: "normal",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Belajar Bareng",
  description: "Generated by create next app",
  icons: {
    icon: "https://mojjracpsjkbntdisrxb.supabase.co/storage/v1/object/public/image/icons.png",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${pixel.className} antialiased bg-primary text-white`}>{children}</body>
    </html>
  )
}
